name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-hello-dir:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello script
        run: ./.github/scripts/hello.sh
        shell: bash